In [1]:
from src.components.utils import *

In [2]:
entries = read_json("../data/entries.json")
entries

,_id,noise,sysTime,device,dateString,rssi,date,sgv,direction,unfiltered,filtered,type,utcOffset,scale,slope,intercept
0,1670830457083e714d391d71,1.0,2022-12-12T07:34:17.000Z,DEXCOM52,2022-12-12T07:34:17.000Z,100.0,1.670830e+12,156.0,Flat,171020.0,171972.0,sgv,0,NaN,NaN,NaN
1,1670829857504d574c2e41ad,1.0,2022-12-12T07:24:17.000Z,DEXCOM52,2022-12-12T07:24:17.000Z,100.0,1.670830e+12,157.0,FortyFiveDown,171156.0,176902.0,sgv,0,NaN,NaN,NaN
2,16708289569215b8b9471a93,1.0,2022-12-12T07:09:16.000Z,DEXCOM52,2022-12-12T07:09:16.000Z,100.0,1.670829e+12,166.0,Flat,179554.0,181458.0,sgv,0,NaN,NaN,NaN
3,1670829555675af8d53dbbc6,1.0,2022-12-12T07:19:15.000Z,DEXCOM52,2022-12-12T07:19:15.000Z,100.0,1.670830e+12,163.0,Flat,176868.0,178942.0,sgv,0,NaN,NaN,NaN
4,1670828657589b6156405dda,1.0,2022-12-12T07:04:17.000Z,DEXCOM52,2022-12-12T07:04:17.000Z,100.0,1.670829e+12,167.0,Flat,180642.0,180642.0,sgv,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13459,1675051678766f58ba6c3a1b,1.0,2023-01-30T04:07:58.000Z,DEXCOM52,2023-01-30T04:07:58.000Z,100.0,1.675052e+12,110.0,Flat,152932.0,156774.0,sgv,0,NaN,NaN,NaN
13460,1675051978899410615f78b4,1.0,2023-01-30T04:12:58.000Z,DEXCOM52,2023-01-30T04:12:58.000Z,100.0,1.675052e+12,108.0,Flat,151028.0,154190.0,sgv,0,NaN,NaN,NaN
13461,16750522802148a05e89b179,1.0,2023-01-30T04:18:00.000Z,DEXCOM52,2023-01-30T04:18:00.000Z,100.0,1.675052e+12,107.0,Flat,150348.0,152048.0,sgv,0,NaN,NaN,NaN
13462,16750525801888c388906857,1.0,2023-01-30T04:23:00.000Z,DEXCOM52,2023-01-30T04:23:00.000Z,100.0,1.675053e+12,108.0,Flat,151470.0,150790.0,sgv,0,NaN,NaN,NaN
13463,16750528810752a82b26cc52,1.0,2023-01-30T04:28:01.000Z,DEXCOM52,2023-01-30T04:28:01.000Z,100.0,1.675053e+12,113.0,Flat,155380.0,150926.0,sgv,0,NaN,NaN,NaN

In [3]:
treatments = read_json("../data/treatments.json")
treatments

,_id,amount,rate,timestamp,enteredBy,created_at,eventType,duration,temp,absolute,...,notes,glucose,glucoseType,unabsorbed,programmed,type,absorptionTime,reason,correctionRange,insulinNeedsScaleFactor
0,{'$oid': '6396db3aabbfb1132e1c40d6'},0.15,2.35,2022-12-12T06:59:03Z,loop://iPhone,2022-12-12T06:59:03.000Z,Temp Basal,4.057136,absolute,2.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '6396db3aabbfb1132e1c40d8'},0.10,1.70,2022-12-12T07:03:06Z,loop://iPhone,2022-12-12T07:03:06.000Z,Temp Basal,4.060481,absolute,1.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '6396db3aabbfb1132e1c40da'},0.05,1.00,2022-12-12T07:07:10Z,loop://iPhone,2022-12-12T07:07:10.000Z,Temp Basal,4.065975,absolute,1.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '6396db3aabbfb1132e1c40dc'},0.05,0.80,2022-12-12T07:11:14Z,loop://iPhone,2022-12-12T07:11:14.000Z,Temp Basal,4.376655,absolute,0.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '6396db3aabbfb1132e1c40de'},0.00,0.45,2022-12-12T07:15:36Z,loop://iPhone,2022-12-12T07:15:36.000Z,Temp Basal,0.036001,absolute,0.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8637,{'$oid': '63d739a2abbfb1132e5b0d40'},0.10,1.45,2023-01-30T03:29:37Z,loop://iPhone,2023-01-30T03:29:37.000Z,Temp Basal,4.770603,absolute,1.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8638,{'$oid': '63d73bbaabbfb1132e5b0f41'},NaN,0.00,2023-01-30T03:34:15Z,loop://iPhone,2023-01-30T03:34:15.000Z,Temp Basal,0.000000,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8639,{'$oid': '63d73bcaabbfb1132e5b0f5b'},0.00,0.00,2023-01-30T03:38:49Z,loop://iPhone,2023-01-30T03:38:49.000Z,Temp Basal,0.036004,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8640,{'$oid': '63d73bccabbfb1132e5b0f60'},0.00,0.00,2023-01-30T03:38:52Z,loop://iPhone,2023-01-30T03:38:52.000Z,Temp Basal,23.968874,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8641,{'$oid': '63d7416aabbfb1132e5b14b5'},0.00,0.00,2023-01-30T04:02:50Z,loop://iPhone,2023-01-30T04:02:50.000Z,Temp Basal,25.437148,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
tmp_basal = treatments[treatments["eventType"] == "Temp Basal"]

,_id,amount,rate,timestamp,enteredBy,created_at,eventType,duration,temp,absolute,...,notes,glucose,glucoseType,unabsorbed,programmed,type,absorptionTime,reason,correctionRange,insulinNeedsScaleFactor
0,{'$oid': '6396db3aabbfb1132e1c40d6'},0.15,2.35,2022-12-12T06:59:03Z,loop://iPhone,2022-12-12T06:59:03.000Z,Temp Basal,4.057136,absolute,2.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '6396db3aabbfb1132e1c40d8'},0.10,1.70,2022-12-12T07:03:06Z,loop://iPhone,2022-12-12T07:03:06.000Z,Temp Basal,4.060481,absolute,1.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '6396db3aabbfb1132e1c40da'},0.05,1.00,2022-12-12T07:07:10Z,loop://iPhone,2022-12-12T07:07:10.000Z,Temp Basal,4.065975,absolute,1.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '6396db3aabbfb1132e1c40dc'},0.05,0.80,2022-12-12T07:11:14Z,loop://iPhone,2022-12-12T07:11:14.000Z,Temp Basal,4.376655,absolute,0.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '6396db3aabbfb1132e1c40de'},0.00,0.45,2022-12-12T07:15:36Z,loop://iPhone,2022-12-12T07:15:36.000Z,Temp Basal,0.036001,absolute,0.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8637,{'$oid': '63d739a2abbfb1132e5b0d40'},0.10,1.45,2023-01-30T03:29:37Z,loop://iPhone,2023-01-30T03:29:37.000Z,Temp Basal,4.770603,absolute,1.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8638,{'$oid': '63d73bbaabbfb1132e5b0f41'},NaN,0.00,2023-01-30T03:34:15Z,loop://iPhone,2023-01-30T03:34:15.000Z,Temp Basal,0.000000,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8639,{'$oid': '63d73bcaabbfb1132e5b0f5b'},0.00,0.00,2023-01-30T03:38:49Z,loop://iPhone,2023-01-30T03:38:49.000Z,Temp Basal,0.036004,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8640,{'$oid': '63d73bccabbfb1132e5b0f60'},0.00,0.00,2023-01-30T03:38:52Z,loop://iPhone,2023-01-30T03:38:52.000Z,Temp Basal,23.968874,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8641,{'$oid': '63d7416aabbfb1132e5b14b5'},0.00,0.00,2023-01-30T04:02:50Z,loop://iPhone,2023-01-30T04:02:50.000Z,Temp Basal,25.437148,absolute,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
read_json("../data/food.json")

Empty DataFrame
Columns: []
Index: []